# ====== 控制与定位 ======
- {ros_topic_name: "/cmd_vel", gz_topic_name: "/fishbot/cmd_vel", ros_type_name: "geometry_msgs/msg/Twist", gz_type_name: "gz.msgs.Twist", direction: "ROS_TO_GZ"}
- {ros_topic_name: "/odom", gz_topic_name: "/fishbot/odometry", ros_type_name: "nav_msgs/msg/Odometry", gz_type_name: "gz.msgs.Odometry", direction: "GZ_TO_ROS"}
- {ros_topic_name: "/tf", gz_topic_name: "/fishbot/tf", ros_type_name: "tf2_msgs/msg/TFMessage", gz_type_name: "gz.msgs.Pose_V", direction: "GZ_TO_ROS"}

# ====== 基础话题 ======
- {gz_topic_name: "/joint_states_gz", ros_topic_name: "/joint_states", gz_type_name: "gz.msgs.Model", ros_type_name: "sensor_msgs/msg/JointState", direction: "GZ_TO_ROS"}
- {gz_topic_name: "/clock", ros_topic_name: "/clock", gz_type_name: "gz.msgs.Clock", ros_type_name: "rosgraph_msgs/msg/Clock", direction: "GZ_TO_ROS"}

# ====== 传感器数据 ======
# 激光雷达
- {gz_topic_name: "/fishbot/scan", ros_topic_name: "/scan", gz_type_name: "gz.msgs.LaserScan", ros_type_name: "sensor_msgs/msg/LaserScan", direction: "GZ_TO_ROS"}
# IMU
- {gz_topic_name: "/fishbot/imu", ros_topic_name: "/imu/data_raw", gz_type_name: "gz.msgs.IMU", ros_type_name: "sensor_msgs/msg/Imu", direction: "GZ_TO_ROS"}
# RGBD 相机图像
- {gz_topic_name: "/fishbot/camera/image", ros_topic_name: "/camera/image_raw", gz_type_name: "gz.msgs.Image", ros_type_name: "sensor_msgs/msg/Image", direction: "GZ_TO_ROS"}